name: tag-filter
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+' # O => v1.0.0 or v.2.2.2 X => v1.0 or 1.0.0

jobs:
  tag-filter:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo hello